#!/bin/sh -e

. /usr/share/debconf/confmodule

# FQDN
while true; do
    db_input critical vaultier/domain
    db_go
    db_get vaultier/domain
    if [ ! -z $RET ]; then
        break
    fi
done

# Email settings
db_input high vaultier/email_host
db_input high vaultier/email_port
db_input high vaultier/email_user
db_input high vaultier/email_password
db_input high vaultier/email_tls
db_go
