#!/bin/bash
set -e

. /usr/share/debconf/confmodule

if [ ! -f /opt/vaultier/vaultier_conf.py ]; then
    # FQDN
    while true; do
        db_input critical vaultier/domain || true
        db_go || true
        db_get vaultier/domain
        if [ ! -z $RET ]; then
            break
        fi
    done

    # database settings
    db_input high vaultier/database_host || true
    db_input high vaultier/database_port || true
    db_input high vaultier/database_name || true
    db_input high vaultier/database_user || true
    db_go || true

    while true; do
        db_input critical vaultier/database_password || true
        db_go || true
        db_get vaultier/database_password
        if [ ! -z $RET ]; then
            break
        fi
    done


    # Email settings
    db_input high vaultier/email_host || true
    db_input high vaultier/email_port || true
    db_input high vaultier/email_user || true
    db_input high vaultier/email_password || true
    db_input high vaultier/email_tls || true

    # Application settings
    db_input high vaultier/allow_registration || true
    db_input high vaultier/allow_statistics || true
    db_go || true

fi