#!/bin/bash
set -e

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    db_purge
fi

if [ "$1" = "remove" ]; then
   . /usr/share/debconf/confmodule
   db_purge
fi

# start servers again
service uwsgi start
service nginx start