#!/bin/bash
set -e

# Stop uWSGI
if [ -f /etc/init.d/uwsgi ]; then
    service uwsgi stop
fi

# Stop Nginx
if [ -f /etc/init.d/nginx ]; then
    service nginx stop
fi

# Stop Apache2
if [ -f /etc/init.d/apache2 ]; then
    service apache2 stop
fi

