#!/bin/bash
set -e

. /usr/share/debconf/confmodule

# stop servers for a little while
service uwsgi stop || true
service nginx stop

# stop vaultier background jobs
echo "Stopping Vaultier background services"
supervisorctl stop vaultier:*