#!/bin/bash
set -e

# stop servers for a little while
service uwsgi stop || true
service nginx stop

# stop vaultier background jobs
echo "Stopping Vaultier background services"
supervisorctl stop vaultier:*